# Generated by Django 3.1.7 on 2021-03-20 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.FileField(upload_to='pics/category')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='idesign.category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
                'unique_together': {('slug', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sliderimg', models.FileField(upload_to='pics/slider')),
                ('first_small_heading', models.CharField(max_length=100)),
                ('second_heading', models.CharField(max_length=100)),
                ('third_heading', models.CharField(max_length=100)),
                ('button_text', models.CharField(max_length=100)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_code', models.CharField(default=None, max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('needle', models.IntegerField()),
                ('stitch', models.IntegerField()),
                ('area', models.IntegerField()),
                ('image', models.FileField(upload_to='pics/Product_image')),
                ('price', models.FloatField(default=0)),
                ('design_type', models.CharField(choices=[('.dst', '.DST'), ('.emb', '.EMB')], default='.emb', max_length=15)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('slug', models.SlugField(max_length=200)),
                ('Publish', models.BooleanField()),
                ('Exclusive', models.BooleanField()),
                ('New', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idesign.category')),
                ('wishlist', models.ManyToManyField(blank=True, related_name='userwishlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='pics/Product_image')),
                ('parent_img', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='idesign.web')),
            ],
        ),
        migrations.CreateModel(
            name='PostFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pics/Product_file')),
                ('parent_file', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='idesign.web')),
            ],
        ),
    ]
